Repository SooNolEum/frontend, pull requests merged in 2024-12, with the labels that each got.

#1 Feat: 목소리 녹음 및 전송 기능 구현
  package-lock.json
  package.json
  src/app/master/speech/page.tsx
  src/app/page.tsx
  src/components/master/VoiceRecorder.tsx
  src/lib/api/speech.ts
  src/types/api.ts
  src/types/master.ts
Labels: Feature

#2 Feat: 마스터 정보 입력 및 전송 기능 구현
  package-lock.json
  package.json
  src/app/master/info/page.tsx
  src/app/master/page.tsx
  src/components/common/Modal.tsx
  src/components/master/MasterInfoForm.tsx
  src/components/master/VoiceRecorder.tsx
  src/config/keywords.ts
  src/config/regions.ts
  src/lib/api/speech.ts
  src/store/master.ts
  src/types/api.ts
  src/types/master.ts
Labels: Feature

#3 Feat: Button & Chip 컴포넌트 구현
  package-lock.json
  package.json
  public/volume.svg
  src/app/fonts/Hakgyoansim.otf
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Button.tsx
  src/components/common/Chip.tsx
  src/lib/utils/cn.ts
  src/types/common.ts
  tailwind.config.ts
Labels: Feature

#6 Feat: Master 페이지 UI 구현
  public/file.svg
  public/globe.svg
  public/info_bg.svg
  public/items/구좌읍.svg
  public/items/남원읍.svg
  public/items/대정읍.svg
  public/items/서귀포시.svg
  public/items/성산읍.svg
  public/items/안덕면.svg
  public/items/애월읍.svg
  public/items/제주시.svg
  public/items/조천읍.svg
  public/items/표선면.svg
  public/items/한경면.svg
  public/items/한림읍.svg
  public/master_bg.svg
  public/next.svg
  public/speech_bg.svg
  public/vercel.svg
  public/window.svg
  src/app/master/layout.tsx
  src/app/master/page.tsx
  src/app/master/speech/page.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/master/AudioVisualizer.tsx
  src/components/master/MasterInfoForm.tsx
  src/components/master/ProgressBar.tsx
  src/components/master/VoiceRecorder.tsx
  src/lib/api/speech.ts
  src/types/api.ts
  src/types/common.ts
  src/types/master.ts
  tailwind.config.ts
Labels: Feature

#12 Fix: User 페이지 서버 연동
  src/app/(user)/explore/page.tsx
  src/app/(user)/page.tsx
  src/components/user/CarouselSlide.tsx
  src/components/user/explore/ExploreNav.tsx
  src/components/user/story/FullStory.tsx
  src/components/user/story/QuizModal.tsx
  src/components/user/story/StoryContent.tsx
  src/components/user/story/StoryNav.tsx
  src/lib/api/user.ts
  src/lib/data/explore.ts
  src/types/user.ts
Labels: Fix

#13 Fix: UI 수정 및 API 연동
  public/avatar.svg
  public/name.svg
  public/pocket2.svg
  public/volumeOff.svg
  src/app/(user)/gift/[location]/page.tsx
  src/app/(user)/mypage/page.tsx
  src/components/common/Chip.tsx
  src/components/master/VoiceRecorder.tsx
  src/components/user/CarouselSlide.tsx
  src/components/user/gift/GiftIcon.tsx
  src/components/user/mypage/GiftCount.tsx
  src/components/user/mypage/Name.tsx
  src/components/user/mypage/New.tsx
  src/components/user/mypage/NewStoryNotification.tsx
  src/components/user/mypage/QuestBadgeCollection.tsx
  src/components/user/mypage/UserName.tsx
  src/components/user/story/StoryContent.tsx
  src/components/user/story/StoryNav.tsx
  src/lib/api/speech.ts
  src/lib/api/story.ts
  src/lib/api/user.ts
  src/store/user.ts
  src/types/api.ts
  src/types/common.ts
  src/types/master.ts
  src/types/quiz.ts
  src/types/story.ts
  src/types/user.ts
Labels: Feature, Fix

#15 HOTFIX: master 페이지 버튼 레이아웃 수정
  src/app/master/layout.tsx
  src/app/master/page.tsx
Labels: !HOTFIX

#16 HOTFIX: 이야기 다시듣기 로직 수정
  src/app/(user)/explore/layout.tsx
  src/app/(user)/explore/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/mypage/layout.tsx
  src/components/user/gift/GiftButton.tsx
  src/components/user/mypage/NewStoryNotification.tsx
  src/components/user/mypage/QuestBadgeCollection.tsx
  src/components/user/story/StoryContent.tsx
  src/store/story.ts
  src/types/story.ts
Labels: !HOTFIX

#17 Feat: 각 컴포넌트 레이아웃 추가 및 변경
  public/items/애월읍.svg
  public/items/한경면.svg
  public/ui/collection.svg
  public/ui/gift.svg
  src/app/(user)/explore/layout.tsx
  src/app/(user)/explore/page.tsx
  src/app/(user)/gift/[location]/layout.tsx
  src/app/(user)/gift/[location]/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/mypage/layout.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/page.tsx
  src/app/(user)/story/[id]/layout.tsx
  src/app/(user)/story/[id]/page.tsx
  src/app/globals.css
  src/components/user/Carousel.tsx
  src/components/user/CarouselSlide.tsx
  src/components/user/explore/ExploreNav.tsx
  src/components/user/gift/GiftButton.tsx
  src/components/user/mypage/NewStoryNotification.tsx
  src/components/user/mypage/QuestBadgeCollection.tsx
  src/components/user/mypage/UserName.tsx
  src/components/user/mypage/UserNav.tsx
  src/components/user/story/FullStory.tsx
  src/components/user/story/QuizModal.tsx
  src/components/user/story/StoryButton.tsx
  src/components/user/story/StoryContent.tsx
  src/components/user/story/StoryNav.tsx
Labels: Feature, Fix, Design

#19 Feat: /master 컴포넌트 레이아웃 추가 및 변경
  src/app/master/info/layout.tsx
  src/app/master/layout.tsx
  src/app/master/page.tsx
  src/app/master/speech/layout.tsx
  src/components/master/MasterInfoForm.tsx
  src/components/master/VoiceRecorder.tsx
Labels: Feature, Design

#20 HOTFIX: /master 컴포넌트 레이아웃 추가 및 변경
  src/app/master/info/layout.tsx
  src/app/master/layout.tsx
  src/app/master/page.tsx
  src/app/master/speech/layout.tsx
  src/components/master/MasterInfoForm.tsx
  src/components/master/VoiceRecorder.tsx
Labels: !HOTFIX
